baseURL       = "http://andreeamuresan.com"
languageCode  = "en-us"
title         = "AAM | XR Interaction Design"
theme         = "roxo-hugo"
summarylength = 25
enableEmoji = true

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo-dark.png"
  logo_footer = "images/logo-light.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Andreea Muresan | XR Interaction Design"
  author = "AndreeaMuresan"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/qorR5ay"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "rs"
      title  = "Research"
    [[params.contactForm.projectType]]
      value = "ind"
      title  = "Industry"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/curly-hair-blacked-logo1.png"
    heading               = "I'm an XR Interaction Designer"
    tagline               = "Hello, I'm Andreea! I'm a UI/UX VR researcher, writer, illustrator, but above all else, "
    primary_button        = "See My Projects"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect "
    secondary_button_url  = "contact"


  [params.portfolio]
    enable    = true
    title     = "MY RECENT WORKS"
    subtitle  = "I have over three years of experience conceptualizing and developing XR apps. I focus on hand-tracking experiences that serve as the building blocks of future interfaces. Here are some examples:"
    view_project = "view project"
    more_works = "MORE WORKS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/footer-lights.png"
    title               = ""
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Copenhagen, <br>Denmark"
      email   = "andreea.muresan505@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Google Scholar"
          url  = "https://scholar.google.dk/citations?user=ZKUNLoUAAAAJ&hl=en&authuser=1"
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "https://www.linkedin.com/in/aam505/"
        [[params.footer.social.link]]
          name = "GitHub"
          url  = "https://github.com/aam505"
        [[params.footer.social.link]]
          name = "Twitter/X"
          url  = "https://twitter.com/andreeam505"
        [[params.footer.social.link]]
          name = "YouTube"
          url  = "https://www.youtube.com/channel/UCASIPWR-f4pmDsiSCU4Wrbg"
      # Footer Service
      [params.footer.service]
        title       = "Dedicated to:"
        description = "enhancing workplace experiences through user-centered virtual and augmented reality solutions."
      [params.footer.back_to_top]
        description = "I want to <br> visit again"
